### ISSUE TITLE
PyPI page not up to date

### ISSUE THREAD

**Issue by Freddo3000** [wmellema/Py-SteamCMD-Wrapper#7]
Displays version 1.0.6 as latest, while the github version here is 1.1.0

**Comment by wmellema** [comment]
I'm trying to fix the release stage. Some tests fail at the moment, that's why it hasn't been uploaded to PyPi yet

**Comment by wmellema** [comment]
This issue should be resolved now. My apologies for the long wait! The newest version is 1.1.1 :)
